const affirmationsList = [
  "I am enough. I am whole. I am loved. 💖",
  "My mind is calm. My body is strong. My soul is peaceful. 🌿",
  "I radiate positivity and grace. ✨",
  "Every breath I take fills me with confidence. 🌬️",
  "I release what I cannot control and focus on what I can. 🦋",
  "Today is a fresh start, full of new opportunities. 🌅",
  "I trust the timing of my life. ⏳",
  "My emotions are valid and worthy of attention. 🌊",
  "I am growing into the best version of myself. 🌱",
  "I choose peace over perfection. 🕊️",
  "I forgive myself and set myself free. 💌",
  "I attract love, light, and healing. 💫",
  "I am grounded, centered, and at ease. 🌍",
  "I speak to myself with kindness and compassion. 💗",
  "Everything I need is already within me. 🌟",
  "I allow myself to feel deeply and love fully. ❤️",
  "I am safe in my body and in my world. 🧘‍♀️",
  "I let go of fear and embrace joy. 🌈",
  "Each step I take is one of courage. 🚶‍♀️",
  "I am proud of how far I've come. 🎯",
  "I am worthy of rest and relaxation. 💤",
  "My journey is unfolding with purpose. 📖",
  "I breathe in strength and exhale doubt. 🌬️",
  "My presence is a gift to the world. 🎁",
  "I choose to nourish my mind, body, and soul. 🥗🧠🕊️",
  "I create space for miracles in my life. ✨",
  "I radiate self-respect and inner peace. 🧿",
  "Challenges help me grow and become stronger. 💪",
  "I let go of comparison and celebrate my path. 🎉",
  "My heart is open to give and receive love. 💓",
  "I embrace the unknown with curiosity. 🌌",
  "I am aligned with the rhythm of life. 🎶",
  "I release past hurt and invite in joy. 🎈",
  "I am learning to trust myself fully. 🪞",
  "I am soft, yet powerful. ☁️⚡",
  "Each moment is an opportunity to begin again. 🔄",
  "I bloom with grace, even in tough seasons. 🌸",
  "I honor my needs without guilt. 🔐",
  "My inner light shines brighter each day. 🔅",
  "I deserve to be seen, heard, and valued. 👁️👂💬",
  "I protect my peace with healthy boundaries. 🛡️",
  "I breathe in calm, I breathe out tension. 🌬️",
  "I am becoming exactly who I’m meant to be. 🦋",
  "I welcome abundance into all areas of my life. 💰🌺",
  "My voice matters. My story matters. 📝",
  "I choose to show up fully, with an open heart. 💞",
  "I trust that everything is working out for my highest good. 🌀",
  "I give myself permission to rest and just be. ☕",
  "I am in love with the process of becoming. 🌻",
  "Even small steps move me forward. 🐾",
  "Peace begins within me. ☮️",
  "My worth isn’t defined by productivity. 🧡",
];

export default affirmationsList;